version: "3.8"

services:
  playbook:
    build: .
    container_name: playbook
    restart: unless-stopped
    ports:
      - "3210:80"
    labels:
      icon: https://cdn-icons-png.flaticon.com/512/1087/1087840.png
      com.casaos.title: "Playbook"
      com.casaos.description: "Playbook runner with checklists"
      com.casaos.port: "3210"
